### ISSUE TITLE
Only use vehicle data as ground truth for training and validation ? 

### ISSUE THREAD

**Issue by DRosemei** [nv-tlabs/lift-splat-shoot#10]
Thanks for your great work, but I'm wondering how to get prediction for road and lane segmentation when only use vehicle data to supervise. 
https://github.com/nv-tlabs/lift-splat-shoot/blob/9d15ff2b2b2e83b5c0f9c94e38e23710ef147fc1/src/data.py#L180
binimg visualization below
![image](https://user-images.githubusercontent.com/27892562/124726146-16e5ec00-df40-11eb-9c37-88d4a759b384.png)

**Comment by zhangchbin** [comment]
Hi, the code does not contain the ground-truth for road segmentation and lane segmentation.
So you should implement it by yourself.
I have implemented this, but I don't know why the performance is worse.

**Comment by DRosemei** [comment]
> Hi, the code does not contain the ground-truth for road segmentation and lane segmentation.
> So you should implement it by yourself.
> I have implemented this, but I don't know why the performance is worse.

I got it and thanks.

**Comment by linlion0311** [comment]
> > 嗨，該代號不包含道路分割和車輛分割的基本事實。
> > 所以你應該自己實際發現它。
> > 我已經實際發現了這個，但我不知道為什麼。更巧。
> 
> 我明白了，謝謝。

Hi, can you provide drivable area and lane segmentation code? thanks~
