### ISSUE TITLE
Do we need to train 10000 epochs?

### ISSUE THREAD

**Issue by walterchenchn** [nv-tlabs/lift-splat-shoot#4]
Thanks for you work!

In the paper, you said 300k steps were used to train the network, but in code you use 10000 epochs. Through calculation, I found that 300k steps amount to 43 epochs(in nuScenes trainval dataset), I don't know if something is wrong.

Look forward to your reply!

**Comment by Kevinpgalligan** [comment]
This is late, but I did the same calculation and 43-ish epochs worked fine for me. Same results as the paper. You definitely don't need 10,000 epochs, so I don't know why that's set as the default. Maybe they trained until the accuracy leveled off and then stopped it manually.
